ShopOnline/ShopOnline/Controllers/RegisterController.cs
using Common;
using ShopOnline.BLL;
using ShopOnline.Models;
using ShopOnline.Models.EF;
using ShopOnline.Models.OtherEF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopOnline.Controllers
{
    public class RegisterController : BaseController<xAccount>
    {
        public RegisterController(UnitOfWork unitOfWork) : base(unitOfWork)
        {
        }

        public override ActionResult Index()
        {
            return View();
        }

        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignUp(RegisterRequest register)
        {
            bool IsValid = true;

            if (register == null)
            {
                ModelState.AddModelError("", "Đăng ký không thành công.");
                IsValid = false;
            }
            if (register.Username.IsEmpty())
            {
                ModelState.AddModelError(nameof(register.Username), "Vui lòng nhập tài khoản.");
                IsValid = false;
            }
            if (register.Password.IsEmpty())
            {
                ModelState.AddModelError(nameof(register.Password), "Vui lòng nhập mật khẩu.");
                IsValid = false;
            }
            if (register.ConfirmPassword.IsEmpty())
            {
                ModelState.AddModelError(nameof(register.Password), "Vui lòng nhập lại mật khẩu.");
                IsValid = false;
            }

            if (IsValid)
            {
                if (!register.Password.Equals(register.ConfirmPassword))
                {
                    ModelState.AddModelError("", "Mật khẩu không trùng khớp.");
                    return View("Index");
                }

                if (Instance.CheckExist(register.Username))
                {
                    ModelState.AddModelError("", "Tài khoản đã tồn tại.");
                    return View("Index");
                }

                xPersonnel personnel = new xPersonnel();
                personnel.CreatedDate = DateTime.Now;
                personnel.Status = (int)Define.fStatus.Add;

                xAccount account = new xAccount();
                account.Username = register.Username;
                account.Password = register.Password;
                account.CreatedDate = DateTime.Now;
                account.Status = (int)Define.fStatus.Add;
                account.IsEnable = true;

                try
                {
                    Instance.BeginTransaction();

                    Instance.GetRepository<xPersonnel>().AddOrUpdate(personnel);
                    Instance.SaveChanges();

                    account.IDPersonnel = personnel.KeyID;

                    Instance.GetRepository<xAccount>().AddOrUpdate(account);
                    Instance.SaveChanges();

                    Instance.CommitTransaction();
                }
                catch
                {
                    Instance.RollbackTransaction();
                }

                return RedirectToAction("SignIn", "Login", new { username = register.Username, password = register.Password });
            }
            return View("Index");
        }
    }
}

ShopOnline/ShopOnline/Views/Register/Index.cshtml
@model ShopOnline.Models.OtherEF.RegisterRequest

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Bootstrap Admin Theme</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/Admin/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/Content/Admin/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/Admin/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/Content/Admin/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Đăng ký</h3>
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("SignUp", "Register", FormMethod.Post))
                        {
                            @Html.ValidationSummary(false, "", "error");

                            <form role="form">
                                <fieldset>
                                    <div class="form-group">
                                        @*<input class="form-control" placeholder="Username" name="username" autofocus>*@
                                        @Html.TextBoxFor(m => m.Username, new { @class = "form-control", @placeholder = "Tài khoản", @name = "username", @autofocus = "autofocus" })
                                    </div>
                                    <div class="form-group">
                                        @*<input class="form-control" placeholder="Password" name="password" type="password" value="">*@
                                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Mật khẩu", @name = "password", @value = "" })
                                    </div>
                                    <div class="form-group">
                                        @*<input class="form-control" placeholder="Password" name="password" type="password" value="">*@
                                        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", @placeholder = "Nhập lại mật khẩu", @name = "confirmpassword", @value = "" })
                                    </div>
                                    <!-- Change this to a button or input when using this as a form -->
                                    @*<a href="index.html" class="btn btn-lg btn-success btn-block">Login</a>*@
                                    <button type="submit" class="btn btn-lg btn-success btn-block">Xác nhận</button>
                                    @*<button type="button" class="btn-link pull-right">Đăng ký</button>*@
                                </fieldset>
                            </form>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery -->
    <script src="~/Content/Admin/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/Admin/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Content/Admin/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Content/Admin/dist/js/sb-admin-2.js"></script>
</body>
</html>

ShopOnline/ShopOnline/Views/Register/SignUp.cshtml
@model ShopOnline.Models.OtherEF.RegisterRequest

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Bootstrap Admin Theme</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/Admin/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/Content/Admin/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/Admin/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/Content/Admin/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Đăng ký</h3>
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("SignUp", "Register", FormMethod.Post))
                        {
                            @Html.ValidationSummary(false, "", "error");

                            <form role="form">
                                <fieldset>
                                    <div class="form-group">
                                        @*<input class="form-control" placeholder="Username" name="username" autofocus>*@
                                        @Html.TextBoxFor(m => m.Username, new { @class = "form-control", @placeholder = "Tài khoản", @name = "username", @autofocus = "autofocus" })
                                    </div>
                                    <div class="form-group">
                                        @*<input class="form-control" placeholder="Password" name="password" type="password" value="">*@
                                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Mật khẩu", @name = "password", @value = "" })
                                    </div>
                                    <div class="form-group">
                                        @*<input class="form-control" placeholder="Password" name="password" type="password" value="">*@
                                        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", @placeholder = "Nhập lại mật khẩu", @name = "confirmpassword", @value = "" })
                                    </div>
                                    <!-- Change this to a button or input when using this as a form -->
                                    @*<a href="index.html" class="btn btn-lg btn-success btn-block">Login</a>*@
                                    <button type="submit" class="btn btn-lg btn-success btn-block">Xác nhận</button>
                                    @*<button type="button" class="btn-link pull-right">Đăng ký</button>*@
                                </fieldset>
                            </form>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery -->
    <script src="~/Content/Admin/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/Admin/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Content/Admin/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Content/Admin/dist/js/sb-admin-2.js"></script>
</body>
</html>